### ISSUE TITLE
Errors while onboarding `frontend` app

### ISSUE THREAD

**Issue by seyeong-han** [twelvelabs-io/tl-jockey#68]
I really enjoyed learning and using Video Understanding Models in your API playground and tried to implement the `frontend` app locally.
But, there were some challenges to running it, and I wanna share it by raising this issue.

#### 1. Absence of example `.env` file for `frontend` and `server.js`.
  The `.env` should look like this under `frontend` directory.

```
// For frontend/src/apis/apiConfig.js
REACT_APP_API_MAIN_KEY=tlk_...
// For frontend/server.js
TWELVE_LABS_API_KEY=${REACT_APP_API_MAIN_KEY}
// For frontend/src/apis/streamEventsApis.js
REACT_APP_API_INDEX_ID=<YOUR INDEX ID>
// For frontend/server.js
REACT_APP_PORT=8000
// For frontend/src/apis/apiConfig.js
REACT_APP_BASE_SERVER=http://localhost:8000
// For frontend/src/apis/streamEventsApis.js
REACT_APP_LANGGRAPH_API_URL=http://localhost:8123
REACT_APP_LANGCHAIN_API_KEY=lsv2_...
```
  I created `REACT_APP_LANGGRAPH_API_URL` to connect with `jockey server` sdk. The URL was set as default `http://localhost:8123` by `langgraph-sdk`, but I couldn't connect with `langgraph-sdk` without `apiKey`.  
  [streamEventsApis.js](https://github.com/twelvelabs-io/tl-jockey/blob/1575c5048269cf75033dd271d892509cd0b70811/frontend/src/apis/streamEventsApis.js#L6)
```javascript
const client = new Client({
    apiUrl: process.env.REACT_APP_LANGGRAPH_API_URL,
    apiKey: process.env.REACT_APP_LANGCHAIN_API_KEY,
  });
```

#### 2. Missing `dotenv` package in the `frontend/server.js`

I am using `Ubuntu:22.04` for this implementation. I don't know if Mac OS has the same issue, but to read the `.env`, I needed to add this in the `frontend/server.js`.

```
require("dotenv").config();
```

#### 1. Absence of `LANGSMITH_API_KEY` instruction on `main` branch

I found that the `langchain API key` issue has been solved in this [issue](https://github.com/twelvelabs-io/tl-jockey/blob/ceecf9331aa17ec55e4514404748a339a7d4891b/README.md), but it wasn't merged into the `main` branch.

#### 2. Permission Denied on Composing Up Langgraph

I am working on this project on Ubuntu:22.04 and got this reading permission error in `run_jockey_server()` of [jockey/cli.py](jockey/cli.py). 

```shell
#5 ERROR: error from sender: open /home/young/project/twelvelabs/tl-jockey/.langgraph-data: permission denied
------
 > [langgraph-api internal] load build context:
------
failed to solve: error from sender: open /home/young/project/twelvelabs/tl-jockey/.langgraph-data: permission denied
```

I am using the below command as a temporary workaround. I am gonna work on recognizing the OS to determine what `cli` should be used.
```
langgraph_cli_command = [
        "sudo",
     "/home/young/miniconda3/envs/jockey/bin/langgraph",
        # "langgraph", 
        "up", 
        "-c", langgraph_json_file_path, 
        "-d", compose_file_path, 
        "--recreate", 
        "--verbose"
    ]
```

## Todo
I am going to break down the following issues into different branches.

- [ ] Add `LANGSMITH_API_KEY` instruction in `.env` file to run the `jockey server`.
- [ ] Add `frontend/example.env` & Fix `Client` of `langgraph-sdk` & Add `dotenv` in `frontend/server.js`
- [ ] Fix `langgraph_cli_command` to solve a permission error

**Comment by james-le-twelve-labs** [comment]
@seyeong-han I want to check on this issue. Looks like you still need to replace `react-hls-player` with `react-player` as the final task?
